### ISSUE TITLE
SFS Direct Deposit link is broken

### ISSUE THREAD

**Issue by jonah0** [ninest/husker#80]
Error message:
<img width="427" alt="Screenshot 2024-01-21 at 9 54 03 PM" src="https://github.com/ninest/husker/assets/76494849/0b49e091-bb41-45dc-a71d-c18fbb000563">

**Comment by jonah0** [comment]
The link used is https://neuforms3.neu.edu/lfserver/DirectDeposit.xfm

**Comment by ninest** [comment]
Thank you! This has been updated
